### ISSUE TITLE
Add rendering of special spawn conditions for Witches

### ISSUE THREAD

**Issue by EtlamGit** [Lunatrius/Monster-Spawn-Highlighter#3]
Witches have special spawn conditions in the bounding box of a Swamp Hut, as ONLY witches can spawn there. I would like to have a feature to get these locations rendered in a different way than standard spawn locations (e.g. different color or highlighted border).

I have tried to find a good place in your code to do that, but it seems that you are doing your own spawn condition checking which is slightly different from vanilla code. If I understand your code right, you may miss the special case for Witch spawning completely:
You are calling biome.getSpawnableList( creatureType ) which is only based on the biome, not on special "scattered features" like the Swamp Hut. Instead calling ChunkProviderGenerate.getPossibleCreatures( creatureType, X, Y, Z ) should give a list with Entities that can spawn at that special location. If that list contains only the Witch, we have one of these special locations.

getPossibleCreatures() probably also provide Wither Skeleton spawning locations, but as they do not spawn as exclusive mob at that locations your current rendering would be fine.

**Comment by Lunatrius** [comment]
The mod is no longer being updated, no point keeping this open.

**Comment by EtlamGit** [comment]
Sad to hear, that you stop developing on this mod. I'm still searching for a good monster-spawn-highlighter for current Minecraft...
I wish you a happy Christmas!

**Comment by 0uti** [comment]
that's why i am doing it myself :)

**Comment by Lunatrius** [comment]
@0uti is the functionality roughly the same? I can add a redirect link to your repository/mod homepage if you're like.

**Comment by 0uti** [comment]
my mod has a spawn overlay and chunk grid like NEI (JEI does not provide this feature),
displays the durability of tools in the hotbar also the armor in the upper left corner and
shows jump height, speed and health from horses, mule, etc..

not that big deal :)
